---
abstract: 'fork subtests to run in parallel'
author:
  - 'Nick Cleaton <nick@cleaton.net>'
build_requires:
  Config: 0
  Test::Builder: 0.94
  Test::Cmd: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0.94
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-ParallelSubtest
provides:
  Test::ParallelSubtest:
    file: lib/Test/ParallelSubtest.pm
    version: 0.03_01
  Test::ParallelSubtest::Capture:
    file: lib/Test/ParallelSubtest/Capture.pm
    version: 0.03_01
  Test::ParallelSubtest::CaptureFH:
    file: lib/Test/ParallelSubtest/Capture.pm
requires:
  Carp: 0
  IO::WrapTie: 0
  POSIX: 0
  Sub::Prepend: 0
  TAP::Parser: 0
  Test::Builder: 0.94
  Tie::FileHandle::Base: 0
  perl: 5.006001
resources:
  license: http://dev.perl.org/licenses/
version: 0.03_01
