--- #YAML:1.0
name:               Test-ParallelSubtest
version:            0.05
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Config:               0
    IO::WrapTie:          0
    POSIX:                0
    Sub::Prepend:         0
    TAP::Parser:          0
    Test::Builder:        0.94
    Test::Cmd:            0
    Test::Differences:    0
    Test::Exception:      0
    Test::More:           0.94
    Tie::FileHandle::Base:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
