---
name: Test-ParallelSubtest
version: 0.01
author:
  - 'Nick Cleaton <nick@cleaton.net>'
abstract: fork subtests to run in parallel
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Config: 0
  Test::Builder: 0
  Test::Cmd: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
requires:
  Carp: 0
  IO::WrapTie: 0
  POSIX: 0
  Sub::Prepend: 0
  TAP::Parser: 0
  Test::Builder: 0.94
  Tie::FileHandle::Base: 0
  perl: 5.006001
configure_requires:
  Module::Build: 0.35
provides:
  Test::ParallelSubtest:
    file: lib/Test/ParallelSubtest.pm
    version: 0.01
  Test::ParallelSubtest::Capture:
    file: lib/Test/ParallelSubtest/Capture.pm
    version: 0.01
  Test::ParallelSubtest::CaptureFH:
    file: lib/Test/ParallelSubtest/Capture.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
